flags:
  HsOpenSSL:
    homebrew-openssl: true
    fast-bignum: false
nix:
  shell-file: nix/shell.nix
packages:
- location: .

extra-deps:
- HsOpenSSL-0.11.4.11
- cassava-embed-0.1.0.0
- hasql-1.3.0.2
- hasql-pool-0.5
- http-client-0.5.10
- hw-kafka-client-2.3.3
- katip-rollbar-0.3.0.1
- libssh2-0.2.0.6
- mersenne-random-1.0.0.1
- open-union-0.3.0.0
- prometheus-0.5.0
- rollbar-hs-0.2.0.0
- servant-0.12
- servant-server-0.12
- text-builder-0.5.1.1
- validation-1
- xml-isogen-0.3.0

resolver: lts-10.0
